spring:
  application:
    name: hello

server:
  port: 9001

eureka:
  instance:
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 5
    metadata-map:
      cluster: main
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 3

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF
