spring:
  application:
    name: ribbon

server:
  port: 8002

say-hello:
  ribbon:
    eureka:
      enabled: false
    listOfServers: localhost:8001,localhost:9990,localhost:9991
    ServerListRefreshInterval: 15000
